browser=Chrome

# Project 1 - Amazon

actualAmazonUrl=https://www.amazon.in/
expectedAmazonUrl=https://www.amazon.in/
searchOnAmazon=Bag
actualAmazonXpath=(//div[@data-cy='title-recipe'])[21]
expectedAmazonXpath=(//div[@data-cy='title-recipe'])[21]
actualAmazonText=Added to cart
expectedAmazonText=Added to cart
actualAmazonButtonText=Continue
expectedAmazonButtonText=Continue

# Project 2 - AppliTools.com

appURL=https://demo.applitools.com/
appUsername=Admin
appPassword=Password@123

# Project 3 - Flipkart

actualFlipkartUrl=https://www.flipkart.com/
expectedFlipkartUrl=https://www.flipkart.com/
searchOnFlipkart=Bag
actualFlipkartXpath=(//div[@data-id]//a[contains(@href,'/p/')])[120]
expectedFlipkartXpath=(//div[@data-id]//a[contains(@href,'/p/')])[120]
actualFlipkartText=Add to cart
expectedFlipkartText=Add to cart
actualFlipkartButtonText=Continue
expectedFlipkartButtonText=Continue

# Project 4 - Practice Test Automation

pta_url=https://practicetestautomation.com/practice-test-login/
VALID_USERNAME=student
VALID_PASSWORD=Password123
INVALID_USERNAME=incorrectUser
INVALID_PASSWORD=incorrectPassword
INTENTIONAL_SCREENSHOT=This Title Does Not Exist - Intentional Failure

# Project 5 - SauceDemo

actualSauceDemoUrl=https://www.saucedemo.com/
expectedSauceDemoUrl=https://www.saucedemo.com/
sauceValidUsername=standard_user
sauceValidPassword=secret_sauce
sauceInvalidUsername=standard
sauceInvalidPassword=secret
firstName=First Name
lastName=Last Name
postalCode=123456
expectedProductPageTitle=Products
actualProductPageTitle=Products
expectedCartPageTitle=Your Cart
actualCartPageTitle=Your Cart
expectedInformationPageTitle=Checkout: Your Information
actualInformationPageTitle=Checkout: Your Information
expectedOverviewPageTitle=Checkout: Overview
actualOverviewPageTitle=Checkout: Overview
expectedCompletePageTitle=Complete!
actualCompletePageTitle=Complete!
expectedRedirectProductPageTitle=Products
actualRedirectProductPageTitle=Products
expectedLoginButtonText=Login
actualLoginButtonText=Login